export type CanvasOptions = {
  len: number;
  count: number;
  baseTime: number;
  addedTime: number;
  dieChance: number;
  spawnChance: number;
  sparkChance: number;
  sparkDist: number;
  sparkSize: number;
  color: string;
  baseLight: number;
  addedLight: number;
  shadowToTimePropMult: number;
  baseLightInputMultiplier: number;
  addedLightInputMultiplier: number;
  cx: number;
  cy: number;
  repaintAlpha: number;
  hueChange: number;
};
